# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
dizi = np.array([12, 5, 27, 3, 18])
print("Orijinal array:", dizi)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın
sirali_dizi = np.sort(dizi)
print("Sıralanmış array:", sirali_dizi)


Orijinal array: [12  5 27  3 18]
Sıralanmış array: [ 3  5 12 18 27]


# Problem 2

In [1]:
import numpy as np

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
dizi1 = np.array([10, 15, 30, 45, 60])
print("1:", dizi1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
dizi2 = np.arange(5, 16)
print("2:", dizi2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
dizi3 = np.arange(50, 101, 5)
print("3:", dizi3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
dizi4 = np.zeros(10)
print("4:", dizi4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
dizi5 = np.ones(10)
print("5:", dizi5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
dizi6 = np.linspace(0, 100, 5)
print("6:", dizi6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
dizi7 = np.random.randint(10, 30, size=5)
print("7:", dizi7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
dizi8 = np.random.uniform(-1, 1, 10)
print("8:", dizi8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10, 50, size=(3, 5))
print("9:\n", matris)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplam = matris.sum(axis=1)
sutun_toplam = matris.sum(axis=0)
print("10 - Satır toplamları:", satir_toplam)
print("10 - Sütun toplamları:", sutun_toplam)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print("11 - Max:", matris.max())
print("11 - Min:", matris.min())
print("11 - Ortalama:", matris.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.unravel_index(np.argmax(matris), matris.shape)
print("12 - En büyük değerin indeksi (satır, sütun):", max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi13 = np.arange(10, 21)
print("13 - İlk 3 eleman:", dizi13[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print("14 - Tersten dizi13:", dizi13[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print("15 - İlk satır:", matris[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("16 - 2.satır 3.sütun elemanı:", matris[1, 2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("17 - Tüm satırların ilk elemanı:", matris[:, 0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("18 - Kareleri:\n", matris ** 2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
yeni_matris = np.random.randint(-50, 51, size=(3, 5))
pozitif_ciftler = yeni_matris[(yeni_matris > 0) & (yeni_matris % 2 == 0)]
print("19 - Yeni matris:\n", yeni_matris)
print("19 - Pozitif çift sayılar:", pozitif_ciftler)


1: [10 15 30 45 60]
2: [ 5  6  7  8  9 10 11 12 13 14 15]
3: [ 50  55  60  65  70  75  80  85  90  95 100]
4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6: [  0.  25.  50.  75. 100.]
7: [17 25 11 18 25]
8: [-0.94221604 -0.64108292 -0.19287658  0.97837246  0.16616802  0.66195806
  0.14240152 -0.59222066 -0.14629095  0.0279712 ]
9:
 [[33 16 47 40 49]
 [33 19 32 37 47]
 [49 41 35 33 29]]
10 - Satır toplamları: [185 168 187]
10 - Sütun toplamları: [115  76 114 110 125]
11 - Max: 49
11 - Min: 16
11 - Ortalama: 36.0
12 - En büyük değerin indeksi (satır, sütun): (np.int64(0), np.int64(4))
13 - İlk 3 eleman: [10 11 12]
14 - Tersten dizi13: [20 19 18 17 16 15 14 13 12 11 10]
15 - İlk satır: [33 16 47 40 49]
16 - 2.satır 3.sütun elemanı: 32
17 - Tüm satırların ilk elemanı: [33 33 49]
18 - Kareleri:
 [[1089  256 2209 1600 2401]
 [1089  361 1024 1369 2209]
 [2401 1681 1225 1089  841]]
19 - Yeni matris:
 [[  4 -27  -8  36 -29]
 [ 25  24 -29 -18 -34]
 [-19 -43  21   4  27]]
1